# Generated by Django 2.1.2 on 2018-10-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rescatado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='img/rescatados')),
                ('nombre', models.CharField(max_length=30)),
                ('raza', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('state', models.CharField(choices=[('R', 'Rescatado'), ('D', 'Disponible'), ('A', 'Adoptado')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('email', models.CharField(max_length=40)),
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('numero_telefono', models.IntegerField()),
                ('region', models.CharField(max_length=60)),
                ('comuna', models.CharField(max_length=60)),
                ('tipo_casa', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
