# Generated by Django 2.1.2 on 2018-10-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescatado',
            name='state',
            field=models.CharField(max_length=15),
        ),
    ]
