# Generated by Django 2.1.2 on 2018-10-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_auto_20181029_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescatado',
            name='foto',
            field=models.ImageField(upload_to='rescatados/'),
        ),
    ]
